mutate(hapcode =
         case_when(
           dlphap == "A+" ~ "1",
           dlphap == "A-" ~ "2",
           dlphap == "A3" ~ "3",
           dlphap == "A4" ~ "4",
           dlphap == "A5" ~ "5",
           dlphap == "E1" ~ "6",
           dlphap == "E6" ~ "7",
           dlphap == "E7" ~ "8",
           dlphap == "E8" ~ "9",
           dlphap == "E9" ~ "10",
           dlphap == "E10" ~ "11",
           dlphap == "E11" ~ "12",
           dlphap == "E12" ~ "13",
           dlphap == "E13" ~ "14",
           dlphap == "E14" ~ "15",
           dlphap == "E15" ~ "16",
           dlphap == "E2" ~ "17",
           dlphap == "E3" ~ "18",
           dlphap == "E4" ~ "19",
           dlphap == "F2" ~ "20",
           dlphap == "F1" ~ "21",
           dlphap == "F3" ~ "22",
           dlphap == "F4" ~ "23",
           dlphap == "F5" ~ "24",
           dlphap == "F6" ~ "25",
           dlphap == "E5" ~ "26",
           dlphap == "F7" ~ "27",
           dlphap == "F8" ~ "28",
           dlphap == "F9" ~ "29"
         ))
